C= gcc
CFLAGS = -std=gnu99 -Wall -g #-DDEBUG

all:
#	$(CC) $(CFLAGS) -o heap-test heap-test.c
#	$(CC) $(CFLAGS) -o pipe-test pipe-test.c
#	$(CC) $(CFLAGS) -o pipes pipes.c
#	$(CC) $(CFLAGS) -o upper upper.c
#	$(CC) $(CFLAGS) -o tokens tokens.c
	$(CC) $(CFLAGS) -o buffOver buffOver.c

.PHONY: clean
clean:
	/bin/rm -rf  buffOver.dSYM buffOver heap-test heap-test.dSYM pipe-test pipe-test.dSYM pipes pipes.dSYM upper upper.dSYM tokens tokens.dSYM

